In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [178]:
data=pd.read_csv("C:/Users/NIKHIL/Desktop/Tution Classes/Linear Regression/HousingData.csv")
data=data.dropna(axis=0)
data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222   
5    0.02985   0.0   2.18   0.0  0.458  6.430  58.7  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
499  0.17783   0.0   9.69   0.0  0.585  5.569  73.5  2.3999    6  391   
500  0.22438   0.0   9.69   0.0  0.585  6.027  79.7  2.4982    6  391   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
5       18.7  394.12   5.21  28.7  
..       ...     ...    ...   ...  
499     19.2  395.77  15.10  17.5  
500     19.2  396.90  14.33  16.8  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  

[394 rows x 14 columns]

In [179]:
data.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  394.000000  394.000000  394.000000  394.000000  394.000000  394.000000   
mean     3.690136   11.460660   11.000863    0.068528    0.553215    6.280015   
std      9.202423   23.954082    6.908364    0.252971    0.113112    0.697985   
min      0.006320    0.000000    0.460000    0.000000    0.389000    3.561000   
25%      0.081955    0.000000    5.130000    0.000000    0.453000    5.879250   
50%      0.268880    0.000000    8.560000    0.000000    0.538000    6.201500   
75%      3.435973   12.500000   18.100000    0.000000    0.624000    6.605500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  394.000000  394.000000  394.000000  394.000000  394.000000  394.000000   
mean    68.932741    3.805268    9.403553  406.431472   18.537563  358.490939   
std     27.888705    2.098571    8.633451  168.312419    2.166460   89.283295   
min      2.900000    1.129600    1.000000  187.000000   12.600000    2.600000   
25%     45.475000    2.110100    4.000000  280.250000   17.400000  376.707500   
50%     77.700000    3.199200    5.000000  330.000000   19.100000  392.190000   
75%     94.250000    5.116700   24.000000  666.000000   20.200000  396.900000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  394.000000  394.000000  
mean    12.769112   22.359645  
std      7.308430    9.142979  
min      1.730000    5.000000  
25%      7.125000   16.800000  
50%     11.300000   21.050000  
75%     17.117500   25.000000  
max     37.970000   50.000000

In [180]:
x=data.iloc[:,:13]
x.shape

(394, 13)

In [181]:
y=data.iloc[:,13]
y.shape

(394,)

In [182]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(x)

In [183]:
X

array([[-0.40081837,  0.27334191, -1.25962   , ..., -1.49630294,
         0.43074011, -1.06712587],
       [-0.39853454, -0.47905119, -0.56972405, ..., -0.3408793 ,
         0.43074011, -0.49719648],
       [-0.39853672, -0.47905119, -0.56972405, ..., -0.3408793 ,
         0.38509692, -1.19727801],
       ...,
       [-0.3965804 , -0.47905119,  0.13466553, ...,  1.13806296,
         0.43074011, -0.50541662],
       [-0.39489501, -0.47905119,  0.13466553, ...,  1.13806296,
         0.43074011, -0.97670438],
       [-0.38958205, -0.47905119,  0.13466553, ...,  1.13806296,
         0.39204993, -0.86162248]])

In [184]:
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.2)

In [185]:
X_train.shape

(315, 13)

In [186]:
X_test.shape

(79, 13)

In [187]:
X_temp=np.ones(X_train.shape[0])
X_temp.shape

(315,)

In [188]:
X_train=np.insert(X_train,0,X_temp,axis=1)

In [190]:
X_train.shape

array([[ 1.        , -0.34417329, -0.47905119, ..., -0.52574708,
         0.2636434 , -1.11507666],
       [ 1.        , -0.39613974,  0.90033615, ..., -0.06357763,
         0.43074011, -0.71777012],
       [ 1.        ,  0.75964135, -0.47905119, ...,  0.76832739,
        -3.53741421,  1.53591699],
       ...,
       [ 1.        , -0.39185173,  0.39874076, ..., -0.80304875,
         0.41571262,  0.09328324],
       [ 1.        ,  0.61354752, -0.47905119, ...,  0.76832739,
         0.43074011,  0.73445379],
       [ 1.        ,  0.20574344, -0.47905119, ...,  0.76832739,
        -2.8967273 ,  0.47277948]])

In [150]:
########hypothesis function
def hypothesis(theta,x):
    return x.dot(theta)

In [151]:
#######loss function
def loss(X,Y,theta):
    m=X.shape[0]
    y_=hypothesis(theta,X)
#     print(y_.shape)
#     print(y.shape)
    los=np.sum((y_-Y)**2)
    return los/m
    
    

In [152]:
###gradient descent method
def gradient_descent(x,y,learning_rate=0.31,epochs=10):
    m=x.shape[0]
    l=[]
    theta=np.zeros((X_train.shape[1]))
    for i in range(epochs):
        y_=hypothesis(theta,x)
        los=loss(x,y,theta)
        l.append(los)
        grad=((y_-y).dot(x))/m
        theta=theta-learning_rate*grad
    return theta,l
        
        
    

In [153]:
theta,l=gradient_descent(X_train,Y_train)

In [154]:
theta

array([-1.37182639,  0.75675727,  0.3433685 , -0.25690889, -1.40154755,
        3.64843027, -1.39164086, -2.20864392,  1.129203  , -0.86312655,
       -2.21535003,  0.89662565, -1.3423812 ])